### ISSUE TITLE
Admin Dashboard: Basic Statistics

### ISSUE THREAD

**Issue by markusphil** [OpenTechSchool-Leipzig/poll_app#36]
We are now able to store the participants answers to the poll but don't use this data yet.
For each Poll there should be a statistics view, which shows detailed information about the related answers.

basic information
- Date and Title of the workshop
- Total number of participiants.

detailed information per question
- open question => list of all answers
- multiple choice => absolute and relative frequency
- scale question => median and mean value 

## Update (17.11.19)

The poll and answer data is now available on the statistics view. So you could go right ahead and do calculations and charts based on that! 😊 

## Update (23.11.19)

I installed ApexCharts and played around with different Chart types and set up some basic statistics for Multiple Choice and Scale Questions. There is still a lot of room for improvements - and we could also explore different aproaches. If you want to work on this feel free to join me! 😊  

---
## ToDo

- [x] populate polldata with answerdata
- [x] add statistics view
- [X] add poll selection
- [x] select poll data from route => link from the dashboard
- [x] choose a library for charts
- [x] do statistic calculations per questions..
- [x] display data
- [x] create beautiful charts

---
## Chart Libraries

I think that [chart.js](https://github.com/chartjs/Chart.js) or [apexcharts.js](https://github.com/apexcharts/apexcharts.js) might be good options. There are vue wrappers around for both libarieres, while on the first glance I think that the apexcharts wrapper is more convenient to use. apexcharts also seems to have the better documentation, while on the other charts.js has a bigger comunity and it's bundle size is half of apex'.

What do you think?
