### ISSUE TITLE
[Refactor] improve structure to make style adjustments easier

### ISSUE THREAD

**Issue by markusphil** [OpenTechSchool-Leipzig/poll_app#60]
## Guidline

- Provide global variables and mixins for reused values and properties
- move duplicate code to reusable components to get all styling at one place
- if style hast to be repeated in multiple components provide global classes

---
## Tasks

- [x] create gloable classes for poll input
- [x] make use of bulma columns for organizing UI Elements
- [x] setup a container component for all displayed list (header, body-slot, controls-slot)
- [x] use container component for all sections
- [x] finish #62 ...
- [x] to finalize the rework of the `add question` component
